<a href="https://colab.research.google.com/github/e-hkr/SR_practice/blob/main/metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 準備

In [ ]:
# imports
import pickle
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error

In [ ]:
BASE_DIR = 'xxx'

# データの読み込み
with open(f'{BASE_DIR}/results/pred.pickle', 'rb') as f:
  data = pickle.load(f)

In [ ]:
# 自作関数
def psnr(pred, true) -> float:
  x_max = max(pred.max(),true.max())
  x_min = min(pred.min(),true.min())
  return -10 * np.log10(mean_squared_error((pred-x_min)/(x_max-x_min), (true-x_min)/(x_max-x_min)))


def rmse(pred, true) -> float:
  return mean_squared_error(true, pred, squared=False)


def me(pred, true) -> float:
  return (pred - true).mean()

# 評価指標

__評価指標__  
【凡例】P：降水量、T：気温、R：湿数、U：東西風、V：南北風、W：風速  
【注】東風西風などはバグを含む可能性あり(min,maxで抽出しているので)
1. 降水量全体のPSNR　　　　　　　　　　　 ：PSNR_P
1. 気温全体のPSNR　　　　　　　　　　　　 ：PSNR_T
1. 湿数全体のPSNR　　　　　　　　　　　　 ：PSNR_R
1. 東西風全体のPSNR　　　　　　　　　　　 ：PSNR_U
1. 南北風全体のPSNR　　　　　　　　　　　 ：PSNR_V
1. 風速全体のPSNR　　　　　　　　　　　　 ：PSNR_W
1. 時系列方向積算降水量のRMSE　　　　　　 ：RMSE_CPT
1. 領域積算降水量のRMSE　　　　　　　　　 ：RMSE_CPR
1. 時系列方向最大降水量のRMSE　　　　　　 ：RMSE_XPT
1. 領域最大降水量のRMSE　　　　　　　　　 ：RMSE_XPR
1. 時系列方向99.9%タイル値のRMSE　　　 　 ：RMSE_999
1. 時系列方向10mm/h以上の発生確率のRMSE ：RMSE_10
1. 時系列方向4mm/h以上の発生確率のRMSE　：RMSE_4
1. 時系列方向0.1mm/h以上の発生確率のRMSE ：RMSE_0.1
1. 全平均気温のRMSE　　　　　　　　　　　 ：RMSE_AT
1. 全平均湿数のRMSE　　　　　　　　　　　 ：RMSE_AR
1. 全平均東西風のRMSE　　　　　　　　　　 ：RMSE_AU
1. 時系列方向最大西風のRMSE　　　　　　　 ：RMSE_XUT+
1. 時系列方向最大東風のRMSE　　　　　　　 ：RMSE_XUT-
1. 領域最大西風のRMSE　　　　　　　　　　 ：RMSE_XUR+
1. 領域最大東風のRMSE　　　　　　　　　　 ：RMSE_XUR-
1. 全平均南北風のRMSE　　　　　　　　　　 ：RMSE_AV
1. 時系列方向最大南風のRMSE　　　　　　　 ：RMSE_XVT+
1. 時系列方向最大北風のRMSE　　　　　　　 ：RMSE_XVT-
1. 領域最大南風のRMSE　　　　　　　　　　 ：RMSE_XVR+
1. 領域最大北風のRMSE　　　　　　　　　　 ：RMSE_XVR-
1. 全平均風速のRMSE　　　　　　　　　　　 ：RMSE_AW
1. 時系列方向最大風速のRMSE　　　　　　　 ：RMSE_XWT
1. 領域最大風速のRMSE　　　　　　　　　　 ：RMSE_XWR
1. 降水量全体の相関係数　　　　　　　　　　：CORR_P
1. 気温全体の相関係数　　　　　　　　　　　：CORR_T
1. 湿数全体の相関係数　　　　　　　　　　　：CORR_R
1. 東西風全体の相関係数　　　　　　　　　　：CORR_U
1. 南北風全体の相関係数　　　　　　　　　　：CORR_V
1. 風速全体の相関係数　　　　　　　　　　　：CORR_W

In [ ]:
df = pd.DataFrame(np.zeros((35, 5)), columns=['Input', 'MLP', 'CNN1', 'CNN2', 'CNN3'])
df.index = ['PSNR_P', 'RMSE_CPT', 'RMSE_CPR', 'RMSE_XPT', 'RMSE_XPR', 'RMSE_999', 'RMSE_10', 'RMSE_4', 'RMSE_0.1', 'CORR_P', #9
            'PSNR_T', 'RMSE_AT', 'CORR_T', #12
            'PSNR_R', 'RMSE_AR', 'CORR_R', #15
            'PSNR_U', 'RMSE_AU', 'RMSE_XUT+', 'RMSE_XUT-', 'RMSE_XUR+', 'RMSE_XUR-', 'CORR_U', #22
            'PSNR_V', 'RMSE_AV', 'RMSE_XVT+', 'RMSE_XVT-', 'RMSE_XVR+', 'RMSE_XVR-', 'CORR_V', #29
            'PSNR_W', 'RMSE_AW', 'RMSE_XWT', 'RMSE_XWR', 'CORR_W']#34

In [ ]:
df2 = pd.DataFrame(np.zeros((23, 5)), columns=['Input', 'MLP', 'CNN1', 'CNN2', 'CNN3'])
df2.index = ['ME_CPT', 'ME_CPR', 'ME_XPT', 'ME_XPR', 'ME_999', 'ME_10', 'ME_4', 'ME_0.1', #7
             'ME_AT', #8
             'ME_AR', #9
             'ME_AU', 'ME_XUT+', 'ME_XUT-', 'ME_XUR+', 'ME_XUR-', #14
             'ME_AV', 'ME_XVT+', 'ME_XVT-', 'ME_XVR+', 'ME_XVR-', #19
             'ME_AW', 'ME_XWT', 'ME_XWR']#22

In [ ]:
## PSNR
for j, col in enumerate(df.columns):
  for i, idx in enumerate(df.index[[0,10,13,16,23,30]]):
    df[col][idx] = psnr(data[:,6300*(j+1)+900*i:6300*(j+1)+900*(i+1)], data[:,900*i:900*(i+1)])

In [ ]:
## CORR
for j, col in enumerate(df.columns):
  for i, idx in enumerate(df.index[[9,12,15,22,29,34]]):
    df[col][idx] = np.corrcoef(data[:,6300*(j+1)+900*i:6300*(j+1)+900*(i+1)].reshape(-1), data[:,900*i:900*(i+1)].reshape(-1))[0,1]

In [ ]:
## RMSE_A○, ME_A○
for j, col in enumerate(df.columns):
  for i, (idx,idx2) in enumerate(zip(df.index[[11,14,17,24,31]], df2.index[[8,9,10,15,20]])):
    df[col][idx] = rmse(data[:,6300*(j+1)+900*(i+1):6300*(j+1)+900*(i+2)], data[:,900*(i+1):900*(i+2)])
    df2[col][idx2] = me(data[:,6300*(j+1)+900*(i+1):6300*(j+1)+900*(i+2)], data[:,900*(i+1):900*(i+2)])

In [ ]:
## RMSE_X○T, ME_X○T
for j, col in enumerate(df.columns):
  for i, (idx,idx2) in enumerate(zip(df.index[[18,25,32]], df2.index[[11,16,21]])):
    df[col][idx] = rmse(data[:,6300*(j+1)+900*(i+1):6300*(j+1)+900*(i+2)].max(axis=0), data[:,900*(i+1):900*(i+2)].max(axis=0))
    df2[col][idx2] = me(data[:,6300*(j+1)+900*(i+1):6300*(j+1)+900*(i+2)].max(axis=0), data[:,900*(i+1):900*(i+2)].max(axis=0))
  df[col]['RMSE_XPT'] = rmse(data[:,6300*(j+1):6300*(j+1)+900].max(axis=0), data[:,:900].max(axis=0))
  df2[col]['ME_XPT'] = me(data[:,6300*(j+1):6300*(j+1)+900].max(axis=0), data[:,:900].max(axis=0))

In [ ]:
## RMSE_X○R, ME_X○R
for j, col in enumerate(df.columns):
  for i, (idx,idx2) in enumerate(zip(df.index[[20,27,33]], df2.index[[13,18,22]])):
    df[col][idx] = rmse(data[:,6300*(j+1)+900*(i+1):6300*(j+1)+900*(i+2)].max(axis=1), data[:,900*(i+1):900*(i+2)].max(axis=1))
    df2[col][idx2] = me(data[:,6300*(j+1)+900*(i+1):6300*(j+1)+900*(i+2)].max(axis=1), data[:,900*(i+1):900*(i+2)].max(axis=1))
  df[col]['RMSE_XPR'] = rmse(data[:,6300*(j+1):6300*(j+1)+900].max(axis=1), data[:,:900].max(axis=1))
  df2[col]['ME_XPR'] = me(data[:,6300*(j+1):6300*(j+1)+900].max(axis=1), data[:,:900].max(axis=1))

In [ ]:
## RMSE_X○T-, ME_X○T-
for j, col in enumerate(df.columns):
  for i, (idx,idx2) in enumerate(zip(df.index[[19,26]], df2.index[[12,17]])):
    df[col][idx] = rmse(data[:,6300*(j+1)+900*(i+3):6300*(j+1)+900*(i+4)].min(axis=0), data[:,900*(i+3):900*(i+4)].min(axis=0))
    df2[col][idx2] = me(data[:,6300*(j+1)+900*(i+3):6300*(j+1)+900*(i+4)].min(axis=0), data[:,900*(i+3):900*(i+4)].min(axis=0))

In [ ]:
## RMSE_X○R-, ME_X○R-
for j, col in enumerate(df.columns):
  for i, (idx,idx2) in enumerate(zip(df.index[[21,28]], df2.index[[14,19]])):
    df[col][idx] = rmse(data[:,6300*(j+1)+900*(i+3):6300*(j+1)+900*(i+4)].min(axis=1), data[:,900*(i+3):900*(i+4)].min(axis=1))
    df2[col][idx2] = me(data[:,6300*(j+1)+900*(i+3):6300*(j+1)+900*(i+4)].min(axis=1), data[:,900*(i+3):900*(i+4)].min(axis=1))

In [ ]:
## RMSE_CPT, ME_CPT
for j, col in enumerate(df.columns):
  df[col]['RMSE_CPT'] = rmse(data[:,6300*(j+1):6300*(j+1)+900].sum(axis=0), data[:,:900].sum(axis=0))
  df2[col]['ME_CPT'] = me(data[:,6300*(j+1):6300*(j+1)+900].sum(axis=0), data[:,:900].sum(axis=0))

In [ ]:
## RMSE_CPR, ME_CPR
for j, col in enumerate(df.columns):
  df[col]['RMSE_CPR'] = rmse(data[:,6300*(j+1):6300*(j+1)+900].sum(axis=1), data[:,:900].sum(axis=1))
  df2[col]['ME_CPR'] = me(data[:,6300*(j+1):6300*(j+1)+900].sum(axis=1), data[:,:900].sum(axis=1))

In [ ]:
## RMSE_999, ME_999
for j, col in enumerate(df.columns):
  df[col]['RMSE_999'] = rmse(np.percentile(data[:,6300*(j+1):6300*(j+1)+900], q=99.9, axis=0), np.percentile(data[:,:900], q=99.9, axis=0))
  df2[col]['ME_999'] = me(np.percentile(data[:,6300*(j+1):6300*(j+1)+900], q=99.9, axis=0), np.percentile(data[:,:900], q=99.9, axis=0))

In [ ]:
## RMSE_○, ME_○
for j, col in enumerate(df.columns):
  df[col]['RMSE_10'] = rmse(np.count_nonzero(data[:,6300*(j+1):6300*(j+1)+900]>10.0, axis=0)/len(data), np.count_nonzero(data[:,:900]>10.0, axis=0)/len(data))
  df[col]['RMSE_4'] = rmse(np.count_nonzero(data[:,6300*(j+1):6300*(j+1)+900]>4.0, axis=0)/len(data), np.count_nonzero(data[:,:900]>4.0, axis=0)/len(data))
  df[col]['RMSE_0.1'] = rmse(np.count_nonzero(data[:,6300*(j+1):6300*(j+1)+900]>0.1, axis=0)/len(data), np.count_nonzero(data[:,:900]>0.1, axis=0)/len(data))
  df2[col]['ME_10'] = me(np.count_nonzero(data[:,6300*(j+1):6300*(j+1)+900]>10.0, axis=0)/len(data), np.count_nonzero(data[:,:900]>10.0, axis=0)/len(data))
  df2[col]['ME_4'] = me(np.count_nonzero(data[:,6300*(j+1):6300*(j+1)+900]>4.0, axis=0)/len(data), np.count_nonzero(data[:,:900]>4.0, axis=0)/len(data))
  df2[col]['ME_0.1'] = me(np.count_nonzero(data[:,6300*(j+1):6300*(j+1)+900]>0.1, axis=0)/len(data), np.count_nonzero(data[:,:900]>0.1, axis=0)/len(data))

In [ ]:
df

                 Input         MLP        CNN1        CNN2         CNN3
PSNR_P       39.026546   39.065106   39.550378   39.870441    43.284731
RMSE_CPT   1425.099121  255.539642  486.420654  475.218079  1220.734985
RMSE_CPR    873.349365  862.601868  740.984131  675.579590   709.989746
RMSE_XPT     49.280540   49.149952   45.235950   43.151833    33.734364
RMSE_XPR      8.899266    8.862064    8.687263    8.578614     8.621732
RMSE_999     18.523600   18.378004   16.320567   14.196468    12.764807
RMSE_10       0.006348    0.006316    0.005344    0.003592     0.002878
RMSE_4        0.011122    0.010490    0.005849    0.004021     0.004253
RMSE_0.1      0.018648    0.774772    0.297295    0.215305     0.437096
CORR_P        0.555495    0.555679    0.602103    0.633932     0.626040
PSNR_T       32.218285   35.415852   35.081410   37.170360    37.538681
RMSE_AT       1.704742    1.179724    1.226034    0.963951     0.923929
CORR_T        0.988171    0.993991    0.993521    0.996256     0.996366
PSNR_R       22.370262   23.185968   24.437678   25.482185    25.271699
RMSE_AR       2.884323    2.625782    2.273387    2.113865     2.065248
CORR_R        0.831208    0.841685    0.883634    0.905179     0.905835
PSNR_U       28.207691   29.523847   31.724367   32.613895    32.342093
RMSE_AU       1.237319    1.069961    0.805230    0.697278     0.706491
RMSE_XUT+     1.668049    0.864082    1.141768    0.796056     0.697698
RMSE_XUT-     1.414910    1.504719    1.695421    2.343859     2.990817
RMSE_XUR+     3.550239    1.958614    1.676633    1.086450     1.078791
RMSE_XUR-     0.877048    0.770059    0.760180    0.650949     0.720439
CORR_U        0.865881    0.895342    0.923568    0.943507     0.942415
PSNR_V       27.763205   28.206756   30.143437   31.192589    31.408932
RMSE_AV       0.995916    0.946334    0.706817    0.626396     0.610987
RMSE_XVT+     2.744951    2.274053    3.199611    3.137934     2.547775
RMSE_XVT-     1.492287    1.487469    1.733500    1.766399     1.309139
RMSE_XVR+     4.079820    3.142083    2.851495    2.306890     2.601916
RMSE_XVR-     1.115987    0.908099    0.902834    0.817301     0.731519
CORR_V        0.847397    0.863424    0.885519    0.914650     0.915846
PSNR_W       23.425498   24.443717   26.656823   27.685387    27.715764
RMSE_AW       1.124612    1.014505    0.768948    0.683075     0.680692
RMSE_XWT      2.046007    1.668136    1.250558    1.192461     1.130893
RMSE_XWR      1.162505    1.019514    1.075927    0.850632     0.780375
CORR_W        0.833485    0.859299    0.893130    0.917024     0.915607

In [ ]:
df2

               Input        MLP       CNN1       CNN2         CNN3
ME_CPT  -1332.663208 -89.179634  -9.988055  81.068314  1024.313232
ME_CPR   -136.917465  -9.162298  -1.026171   8.328924   105.237648
ME_XPT    -42.536877 -42.394939 -38.149696 -38.223343   -24.996702
ME_XPR     -2.389545  -2.169922  -2.070964  -2.012805    -1.892043
ME_999    -17.616723 -17.474788 -15.576166 -13.603625   -12.159688
ME_10      -0.005944  -0.005916  -0.005039  -0.002876    -0.002085
ME_4       -0.010520  -0.009862  -0.004482  -0.002185     0.000854
ME_0.1      0.013491   0.705316   0.281255   0.198272     0.402142
ME_AT       0.402956   0.074107  -0.075821   0.199681     0.043827
ME_AR      -1.002129  -0.045232  -0.088546   0.247707     0.124211
ME_AU       0.295148   0.023822   0.011617  -0.036486     0.077084
ME_XUT+     0.429031   0.100185  -0.493290  -0.384936    -0.347468
ME_XUT-    -0.463915  -0.735254   1.193403   2.140062     2.723136
ME_XUR+    -3.118772  -0.918279  -0.893103  -0.353509    -0.143442
ME_XUR-     0.314383   0.053450   0.402214   0.188593     0.364959
ME_AV      -0.031224   0.011200  -0.003970   0.101954    -0.020584
ME_XVT+    -1.816008  -0.859827  -2.374285   1.519360    -1.870979
ME_XVT-    -1.021650  -0.979228   1.399653   1.458110     0.978978
ME_XVR+    -3.161905  -1.633414  -1.404826  -0.306875    -1.216520
ME_XVR-     0.471699   0.307719   0.533762   0.422734     0.325776
ME_AW       0.535731   0.472048  -0.200191  -0.189242    -0.145597
ME_XWT      1.148798   0.877459  -0.708242  -0.907685    -0.672476
ME_XWR     -0.500061  -0.346956  -0.533771  -0.293426    -0.201055

In [ ]:
df.to_csv(f'{BASE_DIR}/results/metrics.csv')
df2.to_csv(f'{BASE_DIR}/results/me.csv')